In [2]:
import numpy as np
import pandas as pd
import joblib

In [3]:
np.random.randn(3) * 1e-4

array([-2.22662708e-05, -2.33104394e-04,  6.44810487e-05])

In [56]:
class Perceptron:

    weights = []
    eta = 0
    epochs = 0
    
    X = pd.DataFrame()
    y = pd.DataFrame()
    
    error = []
    
    def __init__(self, eta, epochs):
        # initializing small weights
        self.weights = np.random.randn(3) * 1e-4 
        print(f"initial weights before training: \n{self.weights}")
        
        # assigning learning rate
        self.eta = eta
        
        # assigning number of epochs
        self.epochs = epochs     
    
    def activationFunction(self, inputs, weights):
        # z = w2.x2 + w1.x1 + w0.x0
        # z = W*X
        z = np.dot(inputs, weights)  
        # using stepfunction as activation function
        # if z>0, return 1. else return 0
        # np.where(condition, if true, else)
        return np.where(z>0, 1,0)
        
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        """
        Example of X:
        x1 x2 
        0   0
        0   1
        1   0
        1   1
        
        Example of X_with_bias:
        x1 x2 bias
        0   0   -1
        0   1   -1
        1   0   -1
        1   1   -1
        
        X_with_bias is X concatenated with an extra column of -1 
        for concatenation, use np.c_[first array, second array]
        """
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f"X_with_bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            # printing epoch number
            print("__"*10)
            print(f"for epoch: {epoch}")
            print("__"*10)
            
            # predicting y_hat using current weights
            # i.e. forward propagation
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"predicted value after forward propagation: \n{y_hat}")
            
            # calculating error by finding the difference between actual y and predicted y
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            # updating weights to adjust with error
            # i.e. backward propagation
            
            # w = w + del(w)
            # w = w + (eta * error* x)
            # W(3,1) = W(3,1) + eta * error(4,1) * X(4,3)
            # W(3,1) = W(3,1) + eta * X.T(3,4) * error(4,1) 
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: \n{epoch}/{self.epochs} : \n{self.weights}")
            
            print("####"*10)
            
            
    def predict(self, X):
        # adding bias to the input as done in the fit function
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        
        # returning the dot product of the input with the "updated" weights
        return self.activationFunction(X_with_bias, self.weights)
    
    def total_loss(self):
        # calculating the total sum of error
        total_loss = np.sum(self.error)
        print(f"total loss: {total_loss}")
        
        return total_loss
        

In [57]:
def prepare_data(df):
    # dropping y_label to form X
    X = df.drop("y", axis = 1)
    # assigning y_label to form y
    y = df["y"]
    
    return X,y

In [82]:
# preparing dataframe for AND
AND = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y":  [0, 0, 0, 1],
}

# preparing dataframe for OR
OR = {
    "x1": [0, 0, 1, 1],
    "x2": [0, 1, 0, 1],
    "y":  [0, 1, 1, 1],
}

In [83]:
# inputting data including X and y
df = pd.DataFrame(OR)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [84]:
# unpacking X and y
X, y = prepare_data(df)

# setting model parameters
ETA = 0.3
EPOCHS = 10

# creating perceptron model and fitting the model with X and y
model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X, y)
_ = model.total_loss()

initial weights before training: 
[ 2.14756598e-06  1.14041328e-04 -6.73968225e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
____________________
for epoch: 0
____________________
predicted value after forward propagation: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 
0/10 : 
[2.14756598e-06 1.14041328e-04 2.99932603e-01]
########################################
____________________
for epoch: 1
____________________
predicted value after forward propagation: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 
1/10 : 
[ 0.60000215  0.60011404 -0.6000674 ]
########################################
____________________
for epoch: 2
____________________
predicted value after forward propagation: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 
2/10 : 
[ 0.60000215  0.60011404 -0.3000674 ]
#####################

In [85]:
# printing X from training set:
print(X.values)

# checking if the model predicts well on training data
model.predict(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


array([0, 1, 1, 1])

In [91]:
# checking how the model predicts on newly entered data

new_data_1 = np.array([[0,1]])
pred_1 = model.predict(new_data_1)
print(f"input: {new_data_1}")
print(f"output: {pred_1}")
print("__"*10)

new_data_2 = np.array([[1,1]])
pred_2 = model.predict(new_data_2)
print(f"input: {new_data_2}")
print(f"output: {pred_2}")
print("__"*10)

new_data_3 = np.array([[0,0]])
pred_3 = model.predict(new_data_3)
print(f"input: {new_data_3}")
print(f"output: {pred_3}")
print("__"*10)

multiple_inputs = np.array([[1,1], [0,1]])
multiple_outputs = model.predict(multiple_outputs)
print(f"input: {multiple_inputs}")
print(f"output: {multiple_outputs}")

input: [[0 1]]
output: [1]
____________________
input: [[1 1]]
output: [1]
____________________
input: [[0 0]]
output: [0]
____________________


ValueError: shapes (2,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [92]:
inputs = np.array([[1,1], [0,1]])
model.predict(inputs)

array([1, 1])